name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: go build && go get -u github.com/jandelgado/gcov2lcov
      - name: Unit tests
        run: go test -v -coverprofile=coverage.out -covermode=count ./...
      - name: gcov2lcov
        uses: jandelgado/gcov2lcov-action@v1.0.2
        with:
          infile: coverage.out
          outfile: coverage.txt
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.txt
      - name: Test install script
        run: bash ./testing/integration/scripts/test-install.sh
