name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Install yq
        run: |
          mkdir -p $HOME/bin/
          wget https://github.com/mikefarah/yq/releases/download/v4.1.0/yq_linux_amd64 -O $HOME/bin/yq
          chmod +x $HOME/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: go build && go get -u github.com/jandelgado/gcov2lcov github.com/wadey/gocovmerge
      - name: Unit tests
        run: go test -v -coverprofile=unit.out -covermode=set github.com/fallard84/cs-cloud-firewall-bouncer/pkg/...
      - name: Integration tests
        run: ./testing/integration/bouncer/test.sh
      - name: merge coverage
        run: gocovmerge unit.out integration.out > coverage.out
      - name: gcov2lcov
        uses: jandelgado/gcov2lcov-action@v1.0.2
        with:
          infile: coverage.out
          outfile: coverage.txt
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.txt
  scripts:
    name: Test scripts
    runs-on: ubuntu-latest
    container:
      image: jrei/systemd-debian
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test install script
        run: bash ./testing/integration/scripts/test-install.sh
